# Generated by Django 5.1 on 2024-09-07 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Title', models.CharField(max_length=80)),
                ('Task_Description', models.CharField(max_length=255)),
                ('Is_Completed', models.BooleanField(default=False)),
                ('Task_Assign_Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Categories', models.ManyToManyField(to='Category.taskcategorymodel')),
            ],
        ),
    ]
